services:
  accounts:
    image: "bhawesh77/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - moneymanager
  loans:
    image: "bhawesh77/loans:s4"
    container_name: loans-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - moneymanager
  cards:
    image: "bhawesh77/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - moneymanager
networks:
  moneymanager:
    driver: "bridge"