server:
  port: 9000

cards:
  message: "Welcome to MoneyManager cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

build:
  version: "1.1"