server:
  port: 8081

loans:
  message: "Welcome to MoneyManager Loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

build:
  version: "3.0-default"